spring:
  application:
    name: push-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:@spring.profiles.active@}
  config:
    additional-location: "optional:file:./config/"
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      static-locations: "file:./dist/, classpath:/static/" # 优先找本地 dist，找不到找包内 static

server:
  port: 8000
#  yDEHjQUcqGgD
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
