spring:
  application:
    name: push-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:@spring.profiles.active@}
  config:
    additional-location: "optional:file:./config/"
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    context-path: /api
