services:
  push-server:
    image: qingzhoudev/push-server:latest
    container_name: push-server
    ports:
      - "8000:8000"
    volumes:
      - push-server-data:/app/data
    restart: unless-stopped

volumes:
  push-server-data:
